### ISSUE TITLE
feat request: Add ability to respect system dark theme options

### ISSUE THREAD

**Issue by NiceAesth** [michioxd/sounddark#2]
Hey there! I wanted to ask if you would be open to the idea of having the extension follow the OS-wide dark mode setting as an option. I currently use AutoDarkMode on Windows to toggle it based on time of day and having the extension follow that setting would be amazing.

For implementation I was looking at https://github.com/orca-scan/appearance-changed-event or alternatively you could just listen for the `prefers-color-scheme` media query.

Would be open to covering the 5 dollar or whatever fee publishing to the google chrome web store has if you add this. 🙂🚀

**Comment by michioxd** [comment]
Nice idea, added to my task list o⁠(⁠(⁠*⁠^⁠▽⁠^⁠*⁠)⁠)⁠o

**Comment by NiceAesth** [comment]
Thanks so much!
