### ISSUE TITLE
SoundDark 0.2 - error's / bug's

### ISSUE THREAD

**Issue by nuqbe** [michioxd/sounddark#7]
_Hi,
please can you fix this error's / bug's?_

+ _I also attach screenshots with previews_
+ _I use latest Microsoft Edge - Version 128.0.2739.67 (Official build) (64-bit version)_

---

### **1.)** On the page "Likes" is the background wrong color "#fff" instead of "#111111"

> .sc-classic .l-fixed-top-one-column>.l-top {
> background: #fff;

Set "#fff" to "#111111"

+ fixed-top-one-column.css

At "soundcloud.com/you/likes" everything is fine but not on "soundcloud.com/ Profile_ID /likes"

![1 )](https://github.com/user-attachments/assets/85f3f3db-7f7d-4611-8abf-562b9954f02f)

---

### **2.)** The long text in the "Bio" on profile has a wrong color wrapper above the "Show more" button

> background: linear-gradient(hsla(0, 0%, 100%, 0), #fff);

Set "#fff" to "#111111"

+ truncated-description.css

![2 )](https://github.com/user-attachments/assets/c5bc1d73-b90e-4741-b024-34a93e2048f7)

---

### **3.)** In song comments, the artist (uploader) name (nickname) background are shown in white and you can't see the text.

> .commentItem__creator, .commentItem__creatorLink {
> background-color: #f3f3f3;

+ comment-item.css

Set to "#ed6623" or other color

![3 )](https://github.com/user-attachments/assets/b5d2f679-cec0-46fa-85ea-beba37a371a1)

---

### **4.)** In the custom playlist, after click on "Edit" a popup will show the background of the wrong color "#fff"

> .audibleEditForm__form {
> background-color: #fff;

+ audible-edit-form.css

Set "#fff" to "#111111"

![4 )](https://github.com/user-attachments/assets/aaeca349-3fbb-4888-9bd1-2335f98609d0)

_+_

### **4.) (a)** Same popup after click on "Tracks" on the right side of the background under the track time is white.

> .sc-classic .editTrackItem__additional {
> background: linear-gradient(90deg, hsla(0, 0%, 100%, .1), #fff 17px);

+ track-item.css

Set a different color or maybe remove

![4 ) (a)](https://github.com/user-attachments/assets/dce84fb4-f3c6-429b-acb6-a2b6e6b7ae59)

_+_

### **4.) (b)** When you hover mouse over track, it's all white

> editTrackItem sc-type-small m-hover
> 
> .sc-classic .editTrackItem.m-active, .sc-classic .editTrackItem.m-hover {
> background-color: #f2f2f2;

Set to "#2f2f2f" or other color

_+_

### **4.) (c)** Same as "4.) (a)" see screenshot

> .sc-classic .editTrackItem.m-active .editTrackItem__additional, .sc-classic .editTrackItem.m-hover .editTrackItem__additional {
> background: #f2f2f2;
> background: linear-gradient(90deg, hsla(0, 0%, 94.9%, .1), #f2f2f2 17px);

Set same as for "4.) (a)"

4.) (b)+(c):

![4 ) (b)+(c)](https://github.com/user-attachments/assets/4bb70fbf-eb62-4a57-9a6b-80e3ab975b3d)

---

_Thank you so much💗 and I apologize for my bad English.
nuqbe_

**Comment by michioxd** [comment]
Hi, thanks for your issue. I have fixed everything you reported in this issue. Take a look in [this release](https://github.com/michioxd/sounddark/releases/tag/0.3). The extension will be released in store after 7 days of their work, so stay tuned.
